run:
  # default: '1m'
  timeout: '5m'

  # default: []
  build-tags: []

  # default: ''
  modules-download-mode: 'readonly'

  # default: false
  allow-parallel-runners: true

  # default: []
  skip-dirs:
    - local

linters:
  enable:
    - 'asciicheck'
    - 'bodyclose'
    - 'deadcode'
    - 'depguard'
    - 'dogsled'
    - 'errcheck'
    - 'errorlint'
    - 'exportloopref'
    - 'gocritic'
    - 'gofmt'
    - 'gofumpt'
    - 'goheader'
    - 'goimports'
    - 'gomodguard'
    - 'goprintffuncname'
    - 'gosec'
    - 'gosimple'
    - 'govet'
    - 'ineffassign'
    - 'makezero'
    - 'misspell'
    - 'nakedret'
    - 'noctx'
    - 'nolintlint'
    - 'paralleltest'
    - 'prealloc'
    - 'predeclared'
    - 'revive'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'structcheck'
    - 'stylecheck'
    - 'typecheck'
    - 'unconvert'
    - 'unused'
    - 'varcheck'
    - 'whitespace'

issues:
  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
